query xemDanhSachTamTru($input: xemDanhSachTamTruInput!) {
  xemDanhSachTamTru(input: $input) {
    ok
    error {
      mainReason
      message
    }
    paginationOutput {
      totalPages
      totalResults
    }
    tamTru {
      id
      createdAt
      updatedAt
      ngayHetHanTamTru
      ghiChu
      noiTamTruHienTai
    }
  }
}
