query xemDanhSachTamVang($input: xemDanhSachTamVangInput!) {
  xemDanhSachTamVang(input: $input) {
    ok
    error {
      mainReason
      message
    }
    paginationOutput {
      totalPages
      totalResults
    }
    tamVang {
      nguoiTamVang {
        ...UserFragment
      }
      id
      createdAt
      ngayBatDauTamVang
      lyDoTamVang
      diaChiNoiDen
      ngayHetHieuLuc
      updatedAt
    }
  }
}
