query hoKhau {
  xemHoKhauChiTietChoNguoiDung {
    ok
    hoKhau {
      id
      soHoKhau
      createdAt
      diaChiThuongTru
      thanhVien {
        ...UserFragment
      }
    }
    error {
      message
      mainReason
    }
  }
}
