query ThongKeUser {
  thongKeUser {
    ok
    error {
      message
      mainReason
    }
    soNguoiDangKi
    soNguoiDangKiTamTru
    soNguoiDangKiTamVang
    soHo
    soNguoiDuoiLaoDong
    soNguoiTrongLaoDong
    soNguoiTrenLaoDong
  }
}
