query UserDetails($input: XemThongTinNguoiDungChoQuanLiInput!) {
  xemThongTinNguoiDungChoQuanLi(input: $input) {
    ok
    error {
      mainReason
      message
    }
    user {
      ...UserFragment
    }
  }
}
