export enum VaiTroThanhVienBackend {
  ChuHo = "Chủ hộ",
  Vo = "Vợ",
  Chong = "Chồng",
  Con = "Con",
  Bo = "Bố",
  Me = "Mẹ",
  Chau = "Cháu",
  Chat = "Chắt",
  ConNuoi = "Con nuôi",
  Anh = "Anh",
  Chi = "Chị",
  Em = "Em",
  Ong = "Ông",
  Ba = "Bà",
  Khac = "Khác",
}
