export enum VaiTroThanhVienDisplay {
  ChuHo = "Chủ hộ",
  Vo = "Vợ",
  Chong = "Chồng",
  Con = "Con",
  Bo = "Bố",
  Me = "Mẹ",
  Chau = "Cháu",
  Chat = "Chắt",
  ConNuoi = "Con nuôi",
  Anh = "Anh",
  Chi = "Chị",
  Em = "Em",
  Ong = "Ông",
  Ba = "Bà",
  Khac = "Khác",
}
export enum VaitroNguoiDungDisplay {
  Admin = "Admin",
  NguoiDan = "Người dân",
  ToTruong = "Tổ trưởng",
  ToPho = "Tổ phó",
  KeToan = "Kế toán",
}
export enum HanhDongHoKhauDisplay {
  TaoMoiHoKhau = "Tạo mới hộ khẩu",
  CapNhatHoKhau = "Cập nhật hộ khẩu",
  ThemThanhVien = "Thêm thành viên",
  XoaThanhVien = "Xóa thành viên",
  ThayDoiChuHo = "Thay đổi chủ hộ",
  ThayDoiDiaChi = "Thay đổi địa chỉ",
  ThayDoiVaiTro = "Thay đổi vai trò",
  TachHoKhau = "Tách hộ khẩu",
  XoaHoKhau = "Xóa hộ khẩu",
  XoaNguoiKhoiHoKhau = "Xóa người khỏi hộ khẩu",
  DangKyTamVang = "Đăng ký tạm vắng",
}
